name: Docker Build Test

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-hand-gesture:
    name: Build Hand Gesture Addon
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Docker Build
        uses: docker/build-push-action@v6
        with:
          context: ./hand-gesture-addon
          file: ./hand_gesture/Dockerfile
          push: false
